spring:
  application:
    name: EventManager
  jackson:
    time-zone: GMT-04:00
  messages:
    basename: messages
    encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:mock-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:mock-client-secret}
            scope:
              - email
              - profile
  data:
    web:
      pageable:
        page-serialization-mode: via-dto
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/EventManager}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: GMT-04:00
        id:
          new_generator_mappings: true
    show-sql: true
#    MICROMETER/PROMETHEUS
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# Springdoc OpenAPI Config
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

# Custom App Properties
app:
  security:
    master-email: ${MASTER_EMAIL:rt.sotolani@gmail.com}

